// Curated instrument lists for the non-NSE-mainboard data segments bulk-
// uploaded to Blob storage (see lib/blobHistory.ts) -- Commodities, Crypto,
// Forex, Indian indices, International indices, and SME (NSE Emerge)
// stocks. Each symbol carries a pseudo-suffix (".COMM", ".CRYPTO", ".FX",
// ".IDX", ".INTLIDX", ".SME") that lib/blobHistory.ts uses purely to route
// the lookup to the right Blob segment -- these are NOT real Yahoo Finance
// tickers, so there is no live-fetch fallback for them (unlike ".NS"
// stocks, which happen to also be valid Yahoo symbols). That's fine: every
// symbol here is guaranteed to exist in Blob storage since this list is
// generated from the same source data that was uploaded.
//
// Commodity/Crypto/Forex/Index names are hand-labeled (small, fixed
// lists); SME names come from NSE's own SME_EQUITY_L.csv (SYMBOL,
// NAME_OF_COMPANY), the same pattern used for lib/screenerUniverse.ts.

export interface MarketInstrument {
  symbol: string;
  name: string;
}

export interface MarketSegment {
  key: string;
  label: string;
  instruments: MarketInstrument[];
}

export const OTHER_MARKETS: MarketSegment[] = [
  {
    key: "commodity",
    label: "Commodities",
    instruments: [
  { symbol: "ALUMINI.COMM", name: "Aluminium Mini" },
  { symbol: "ALUMINIUM.COMM", name: "Aluminium" },
  { symbol: "COPPER.COMM", name: "Copper" },
  { symbol: "COTTON.COMM", name: "Cotton" },
  { symbol: "CRUDEOIL.COMM", name: "Crude Oil" },
  { symbol: "CRUDEOILM.COMM", name: "Crude Oil Mini" },
  { symbol: "GOLD.COMM", name: "Gold" },
  { symbol: "GOLDGUINEA.COMM", name: "Gold Guinea" },
  { symbol: "GOLDM.COMM", name: "Gold Mini" },
  { symbol: "GOLDPETAL.COMM", name: "Gold Petal" },
  { symbol: "GOLDTEN.COMM", name: "Gold (10g)" },
  { symbol: "NATGASMINI.COMM", name: "Natural Gas Mini" },
  { symbol: "NATURALGAS.COMM", name: "Natural Gas" },
  { symbol: "SILVER.COMM", name: "Silver" },
  { symbol: "SILVERM.COMM", name: "Silver Mini" },
  { symbol: "SILVERMIC.COMM", name: "Silver Micro" },
    ],
  },
  {
    key: "crypto",
    label: "Crypto",
    instruments: [
  { symbol: "BITCOIN.CRYPTO", name: "Bitcoin" },
  { symbol: "BNB.CRYPTO", name: "BNB" },
  { symbol: "ETHEREUM.CRYPTO", name: "Ethereum" },
  { symbol: "SOLANA.CRYPTO", name: "Solana" },
  { symbol: "TETHER_GOLD.CRYPTO", name: "Tether Gold" },
    ],
  },
  {
    key: "forex",
    label: "Forex",
    instruments: [
  { symbol: "CNYINR.FX", name: "Chinese Yuan / Indian Rupee" },
  { symbol: "EURINR.FX", name: "Euro / Indian Rupee" },
  { symbol: "GBPINR.FX", name: "British Pound / Indian Rupee" },
  { symbol: "JPYINR.FX", name: "Japanese Yen / Indian Rupee" },
  { symbol: "USDINR.FX", name: "US Dollar / Indian Rupee" },
    ],
  },
  {
    key: "indexes",
    label: "Indian Indices",
    instruments: [
  { symbol: "BANKNIFTY.IDX", name: "Nifty Bank" },
  { symbol: "FINNIFTY.IDX", name: "Nifty Financial Services (FINNIFTY)" },
  { symbol: "INDIAVIX.IDX", name: "India VIX" },
  { symbol: "MIDCPNIFTY.IDX", name: "Nifty Midcap Select" },
  { symbol: "NIFTY.IDX", name: "Nifty 50" },
  { symbol: "NIFTYFPI.IDX", name: "Nifty FPI" },
  { symbol: "NIFTYNXT50.IDX", name: "Nifty Next 50" },
  { symbol: "NIFTY_100.IDX", name: "Nifty 100" },
  { symbol: "NIFTY_200.IDX", name: "Nifty 200" },
  { symbol: "NIFTY_500.IDX", name: "Nifty 500" },
  { symbol: "NIFTY_AUTO.IDX", name: "Nifty Auto" },
  { symbol: "NIFTY_COMMODITIES.IDX", name: "Nifty Commodities" },
  { symbol: "NIFTY_FINANCIAL_SERVICES.IDX", name: "Nifty Financial Services" },
  { symbol: "NIFTY_FMCG.IDX", name: "Nifty FMCG" },
  { symbol: "NIFTY_IT.IDX", name: "Nifty IT" },
  { symbol: "NIFTY_OIL_AND_GAS.IDX", name: "Nifty Oil & Gas" },
  { symbol: "NIFTY_PHARMA.IDX", name: "Nifty Pharma" },
  { symbol: "NIFTY_SMALLCAP_100.IDX", name: "Nifty Smallcap 100" },
  { symbol: "SENSEX.IDX", name: "S&P BSE Sensex" },
    ],
  },
  {
    key: "international-indexes",
    label: "International Indices",
    instruments: [
  { symbol: "DJI.INTLIDX", name: "Dow Jones Industrial Average" },
  { symbol: "IXIC.INTLIDX", name: "NASDAQ Composite" },
  { symbol: "SPX.INTLIDX", name: "S&P 500" },
    ],
  },
  {
    key: "sme",
    label: "SME (NSE Emerge)",
    instruments: [
  { symbol: "AAKAAR.SME", name: "Aakaar Medical Technologies Limited" },
  { symbol: "AARADHYA.SME", name: "Aaradhya Disposal Industries Limited" },
  { symbol: "AATMAJ.SME", name: "Aatmaj Healthcare Limited" },
  { symbol: "ABH.SME", name: "ABH Healthcare Limited" },
  { symbol: "ABHAPOWER.SME", name: "Abha Power and Steel Limited" },
  { symbol: "ABSMARINE.SME", name: "ABS Marine Services Limited" },
  { symbol: "ACCENTMIC.SME", name: "Accent Microcell Limited" },
  { symbol: "ACCORD.SME", name: "Accord Synergy Limited" },
  { symbol: "ACCPL.SME", name: "Accretion Pharmaceuticals Limited" },
  { symbol: "ACETEC.SME", name: "Acetech E-Commerce Limited" },
  { symbol: "ACTIVEINFR.SME", name: "Active Infrastructures Limited" },
  { symbol: "ADDICTIVE.SME", name: "Addictive Learning Technology Limited" },
  { symbol: "ADISOFT.SME", name: "Adisoft Technologies Limited" },
  { symbol: "AERON.SME", name: "Aeron Composite Limited" },
  { symbol: "AESTHETIK.SME", name: "Aesthetik Engineers Limited" },
  { symbol: "AGARWALFT.SME", name: "Agarwal Float Glass India Limited" },
  { symbol: "AGARWALTUF.SME", name: "Agarwal Toughened Glass India Limited" },
  { symbol: "AGNI.SME", name: "Agni Green Power Limited" },
  { symbol: "AGUL.SME", name: "A G Universal Limited" },
  { symbol: "AHIMSA.SME", name: "Ahimsa Industries Limited" },
  { symbol: "AILIMITED.SME", name: "Abhishek Integrations Limited" },
  { symbol: "AIMTRON.SME", name: "Aimtron Electronics Limited" },
  { symbol: "AISL.SME", name: "ANI Integrated Services Limited" },
  { symbol: "AKANKSHA.SME", name: "Akanksha Power and Infrastructure Limited" },
  { symbol: "AKIKO.SME", name: "Akiko Global Services Limited" },
  { symbol: "ALCODIS.SME", name: "Alcokraft Distilleries Limited" },
  { symbol: "ALLETEC.SME", name: "All E Technologies Limited" },
  { symbol: "ALPEXSOLAR.SME", name: "Alpex Solar Limited" },
  { symbol: "ALUWIND.SME", name: "ALUWIND INFRA-TECH LIMITED" },
  { symbol: "AMBAAUTO.SME", name: "Amba Auto Sales and Services Limited" },
  { symbol: "AMBANIORGO.SME", name: "AMBANI ORGOCHEM LIMITED" },
  { symbol: "AMCL.SME", name: "ANB Metal Cast Limited" },
  { symbol: "AMEYA.SME", name: "Ameya Precision Engineers Limited" },
  { symbol: "AMIABLE.SME", name: "Amiable Logistics (India) Limited" },
  { symbol: "ANAWIL.SME", name: "Anawil Wire and Engineering Limited" },
  { symbol: "ANLON.SME", name: "Anlon Technology Solutions Limited" },
  { symbol: "ANONDITA.SME", name: "Anondita Medicare Limited" },
  { symbol: "ANYA.SME", name: "Anya Polytech & Fertilizers Limited" },
  { symbol: "APEXECO.SME", name: "Apex Ecotech Limited" },
  { symbol: "APRAMEYA.SME", name: "Aprameya Engineering Limited" },
  { symbol: "APS.SME", name: "Australian Premium Solar (India) Limited" },
  { symbol: "APSISAERO.SME", name: "Apsis Aerocom Limited" },
  { symbol: "ARABIAN.SME", name: "Arabian Petroleum Limited" },
  { symbol: "ARCIIL.SME", name: "ARC Insulation & Insulators Limited" },
  { symbol: "ARHAM.SME", name: "Arham Technologies Limited" },
  { symbol: "ARIHANTACA.SME", name: "Arihant Academy Limited" },
  { symbol: "ARISTO.SME", name: "Aristo Bio-Tech And Lifescience Limited" },
  { symbol: "ARMOUR.SME", name: "Armour Security (India) Limited" },
  { symbol: "ARUNAYA.SME", name: "Arunaya Organics Limited" },
  { symbol: "ARVINDPORT.SME", name: "ARVIND PORT AND INFRA LIMITED" },
  { symbol: "ASCOM.SME", name: "Ascom Leasing & Investments Limited" },
  { symbol: "ASHALOG.SME", name: "Ashapura Logistics Limited" },
  { symbol: "ASHUTOSH.SME", name: "Ashutosh Fibre Limited" },
  { symbol: "ASHWINI.SME", name: "Ashwini Container Movers Limited" },
  { symbol: "ASPIRE.SME", name: "Aspire & Innovative Advertising Limited" },
  { symbol: "ATCENERGY.SME", name: "ATC Energies System Limited" },
  { symbol: "ATMASTCO.SME", name: "Atmastco Limited" },
  { symbol: "AUROIMPEX.SME", name: "Auro Impex  & Chemicals Limited" },
  { symbol: "AUSL.SME", name: "Aditya Ultra Steel Limited" },
  { symbol: "AVANA.SME", name: "Avana Electrosystems Limited" },
  { symbol: "AVATAR.SME", name: "AVATAR Industries Limited" },
  { symbol: "AVIANSH.SME", name: "Avi Ansh Textile Limited" },
  { symbol: "AVIENCE.SME", name: "Avience Biomedicals Limited" },
  { symbol: "AVPINFRA.SME", name: "AVP Infracon Limited" },
  { symbol: "AVSL.SME", name: "AVSL Industries Limited" },
  { symbol: "BABAFP.SME", name: "Baba Food Processing (India) Limited" },
  { symbol: "BAGDIGITAL.SME", name: "B.A.G. Convergence Limited" },
  { symbol: "BAHETI.SME", name: "Baheti Recycling Industries Limited" },
  { symbol: "BALAJIPHOS.SME", name: "Balaji Phosphates Limited" },
  { symbol: "BALCO.SME", name: "Solve Plastic Products Limited" },
  { symbol: "BARFLEX.SME", name: "Barflex Polyfilms Limited" },
  { symbol: "BASILIC.SME", name: "Basilic Fly Studio Limited" },
  { symbol: "BAWEJA.SME", name: "Baweja Studios Limited" },
  { symbol: "BEACON.SME", name: "Beacon Trusteeship Limited" },
  { symbol: "BEWLTD.SME", name: "BEW Engineering Limited" },
  { symbol: "BHADORA.SME", name: "Bhadora Industries Limited" },
  { symbol: "BIKEWO.SME", name: "Bikewo Green Tech Limited" },
  { symbol: "BIOPOL.SME", name: "Biopol Chemicals Limited" },
  { symbol: "BIRDYS.SME", name: "Grill Splendour Services Limited" },
  { symbol: "BLUEPEBBLE.SME", name: "Blue Pebble Limited" },
  { symbol: "BLUEWATER.SME", name: "Blue Water Logistics Limited" },
  { symbol: "BMETRICS.SME", name: "Bombay Metrics Supply Chain Limited" },
  { symbol: "BMLL.SME", name: "Bio Medica Laboratories Limited" },
  { symbol: "BOSS.SME", name: "Boss Packaging Solutions Limited" },
  { symbol: "BRACEPORT.SME", name: "Brace Port Logistics Limited" },
  { symbol: "BRANDMAN.SME", name: "Brandman Retail Limited" },
  { symbol: "BULKCORP.SME", name: "Bulkcorp International Limited" },
  { symbol: "C2C.SME", name: "C2C Advanced Systems Limited" },
  { symbol: "CADSYS.SME", name: "Cadsys (India) Limited" },
  { symbol: "CANARYS.SME", name: "Canarys Automations Limited" },
  { symbol: "CBAZAAR.SME", name: "Net Avenue Technologies Limited" },
  { symbol: "CEDAAR.SME", name: "Cedaar Textile Limited" },
  { symbol: "CELLECOR.SME", name: "Cellecor Gadgets Limited" },
  { symbol: "CELLPOINT.SME", name: "Cell Point (India) Limited" },
  { symbol: "CGRAPHICS.SME", name: "Creative Graphics Solutions India Limited" },
  { symbol: "CHAMUNDA.SME", name: "Chamunda Electrical Limited" },
  { symbol: "CHANDAN.SME", name: "Chandan Healthcare Limited" },
  { symbol: "CHAVDA.SME", name: "Chavda Infra Limited" },
  { symbol: "CHETANA.SME", name: "Chetana Education Limited" },
  { symbol: "CKKRETAIL.SME", name: "C K K Retail Mart Limited" },
  { symbol: "CLASSICEIL.SME", name: "Classic Electrodes (India) Limited" },
  { symbol: "CLAYCRAFT.SME", name: "Clay Craft India Limited" },
  { symbol: "CLSL.SME", name: "Crop Life Science Limited" },
  { symbol: "CMNL.SME", name: "Chaman Metallics Limited" },
  { symbol: "CMRSL.SME", name: "Cyber Media Research & Services Limited" },
  { symbol: "COMMITTED.SME", name: "Committed Cargo Care Limited" },
  { symbol: "CONNPLEX.SME", name: "Connplex Cinemas Limited" },
  { symbol: "CONTI.SME", name: "Continental Seeds and Chemicals Limited" },
  { symbol: "COOLCAPS.SME", name: "Cool Caps Industries Limited" },
  { symbol: "CPS.SME", name: "C P S Shapers Limited" },
  { symbol: "CRAYONS.SME", name: "Crayons Advertising Limited" },
  { symbol: "CREDENT.SME", name: "Credent Connect N Care Limited" },
  { symbol: "CSSL.SME", name: "Clear Secured Services Limited" },
  { symbol: "CUDML.SME", name: "Cash Ur Drive Marketing Limited" },
  { symbol: "CURIS.SME", name: "Curis Lifesciences Limited" },
  { symbol: "CURRENT.SME", name: "Current Infraprojects Limited" },
  { symbol: "DANISH.SME", name: "Danish Power Limited" },
  { symbol: "DCCL.SME", name: "Dar Credit & Capital Limited" },
  { symbol: "DCG.SME", name: "DCG Cables & Wires Limited" },
  { symbol: "DECCANTRAN.SME", name: "Deccan Transcon Leasing Limited" },
  { symbol: "DEEM.SME", name: "Deem Roll Tech Limited" },
  { symbol: "DELAPLEX.SME", name: "Delaplex Limited" },
  { symbol: "DELTIC.SME", name: "Delta Autocorp Limited" },
  { symbol: "DENEERS.SME", name: "De Neers Tools Limited" },
  { symbol: "DENTALKART.SME", name: "Vasa Denticity Limited" },
  { symbol: "DESTINY.SME", name: "Destiny Logistics & Infra Limited" },
  { symbol: "DHANLAXMI.SME", name: "Dhanlaxmi Crop Science Limited" },
  { symbol: "DHANSA.SME", name: "Dhansa Labs Limited" },
  { symbol: "DHARARAIL.SME", name: "Dhara Rail Projects Limited" },
  { symbol: "DHARIWAL.SME", name: "Dhariwalcorp Limited" },
  { symbol: "DHTL.SME", name: "Docmode Health Technologies Limited" },
  { symbol: "DIGIKORE.SME", name: "Digikore Studios Limited" },
  { symbol: "DIRL.SME", name: "Dhanuka Infra Realty Limited" },
  { symbol: "DIVINEHIRA.SME", name: "Divine Hira Jewellers Limited" },
  { symbol: "DIVYADHAN.SME", name: "Divyadhan Recycling Industries Limited" },
  { symbol: "DKEGL.SME", name: "D.K. Enterprises Global Limited" },
  { symbol: "DPEL.SME", name: "Divine Power Energy Limited" },
  { symbol: "DRONE.SME", name: "Drone Destination Limited" },
  { symbol: "DRSCARGO.SME", name: "DRS Cargo Movers Limited" },
  { symbol: "DRSDILIP.SME", name: "DRS Dilip Roadlines Limited" },
  { symbol: "DTL.SME", name: "Diensten Tech Limited" },
  { symbol: "DUCOL.SME", name: "Ducol Organics And Colours Limited" },
  { symbol: "DUGLOBAL.SME", name: "DUDIGITAL GLOBAL LIMITED" },
  { symbol: "DURLAX.SME", name: "Durlax Top Surface Limited" },
  { symbol: "DYNAMIC.SME", name: "Dynamic Services & Security Limited" },
  { symbol: "E2ERAIL.SME", name: "E To E Transportation Infrastructure Limited" },
  { symbol: "ECOLINE.SME", name: "Ecoline Exim Limited" },
  { symbol: "EEPL.SME", name: "Eppeltone Engineers Limited" },
  { symbol: "EFACTOR.SME", name: "E Factor Experiences Limited" },
  { symbol: "EFFWA.SME", name: "Effwa Infra & Research Limited" },
  { symbol: "EFORCE.SME", name: "Electro Force (India) Limited" },
  { symbol: "ELGNZ.SME", name: "Eleganz Interiors Limited" },
  { symbol: "EMAPARTNER.SME", name: "EMA Partners India Limited" },
  { symbol: "EMKAYTOOLS.SME", name: "Emkay Taps and Cutting Tools Limited" },
  { symbol: "EMMIL.SME", name: "Energy Mission Machineries (India) Limited" },
  { symbol: "ENCOMPAS.SME", name: "Encompass Design India Limited" },
  { symbol: "ENFUSE.SME", name: "Enfuse Solutions Limited" },
  { symbol: "ENSER.SME", name: "Enser Communications Limited" },
  { symbol: "ENVIRO.SME", name: "Envirotech Systems Limited" },
  { symbol: "EPWINDIA.SME", name: "EPW India Limited" },
  { symbol: "ESCONET.SME", name: "Esconet Technologies Limited" },
  { symbol: "ESFL.SME", name: "Essen Speciality Films Limited" },
  { symbol: "ESPRIT.SME", name: "Esprit Stones Limited" },
  { symbol: "ETL.SME", name: "Emkay Tools Limited" },
  { symbol: "ETML.SME", name: "Emerald Tyre Manufacturers Limited" },
  { symbol: "EXCELLENT.SME", name: "Excellent Wires and Packaging Limited" },
  { symbol: "EXIMROUTES.SME", name: "Exim Routes Limited" },
  { symbol: "FALCONTECH.SME", name: "Falcon Technoprojects India Limited" },
  { symbol: "FASCINATE.SME", name: "Fascinate Textiles Limited" },
  { symbol: "FELIX.SME", name: "Felix Industries Limited" },
  { symbol: "FIDEL.SME", name: "Fidel Softech Limited" },
  { symbol: "FINBUD.SME", name: "Finbud Financial Services Limited" },
  { symbol: "FLYSBS.SME", name: "FlySBS Aviation Limited" },
  { symbol: "FOCE.SME", name: "Foce India Limited" },
  { symbol: "FONEBOX.SME", name: "Fonebox Retail Limited" },
  { symbol: "FORCAS.SME", name: "Forcas Studio Limited" },
  { symbol: "FORGEAUTO.SME", name: "Forge Auto International Limited" },
  { symbol: "FRESHARA.SME", name: "Freshara Agro Exports Limited" },
  { symbol: "FROG.SME", name: "Frog Innovations Limited" },
  { symbol: "FWSTC.SME", name: "Flywings Simulator Training Centre Limited" },
  { symbol: "GAJANAND.SME", name: "Gajanand International Limited" },
  { symbol: "GANESHIN.SME", name: "Ganesh Infraworld Limited" },
  { symbol: "GANGABATH.SME", name: "Ganga Bath Fittings Limited" },
  { symbol: "GCHOTELS.SME", name: "Grand Continent Hotels Limited" },
  { symbol: "GENXAI.SME", name: "GenXAI Analytics Limited" },
  { symbol: "GGBL.SME", name: "Ganesh Green Bharat Limited" },
  { symbol: "GIRIRAJ.SME", name: "Giriraj Civil Developers Limited" },
  { symbol: "GJL.SME", name: "Grover Jewells Limited" },
  { symbol: "GLOBALPET.SME", name: "Global Pet Industries Limited" },
  { symbol: "GML.SME", name: "Galaxy Medicare Limited" },
  { symbol: "GOLDKART.SME", name: "Goldkart Jewels Limited" },
  { symbol: "GOLDSTAR.SME", name: "Goldstar Power Limited" },
  { symbol: "GOYALSALT.SME", name: "Goyal Salt Limited" },
  { symbol: "GPECO.SME", name: "GP Eco Solutions India Limited" },
  { symbol: "GRAPHISAD.SME", name: "Graphisads Limited" },
  { symbol: "GRCL.SME", name: "Gayatri Rubbers And Chemicals Limited" },
  { symbol: "GREENCHEF.SME", name: "Greenchef Appliances Limited" },
  { symbol: "GREENLEAF.SME", name: "Greenleaf Envirotech Limited" },
  { symbol: "GRETEX.SME", name: "Gretex Industries Limited" },
  { symbol: "GSMFOILS.SME", name: "GSM Foils Limited" },
  { symbol: "GSTL.SME", name: "Globesecure Technologies Limited" },
  { symbol: "GURUNANAK.SME", name: "Gurunanak Agriculture India Limited" },
  { symbol: "HAPPY.SME", name: "Happy Steels Limited" },
  { symbol: "HIGREEN.SME", name: "Hi-Green Carbon Limited" },
  { symbol: "HOACFOODS.SME", name: "Hoac Foods India Limited" },
  { symbol: "HOLMARC.SME", name: "Holmarc Opto-Mechatronics Limited" },
  { symbol: "HOMESFY.SME", name: "Homesfy Realty Limited" },
  { symbol: "HPTL.SME", name: "HP Telecom India Limited" },
  { symbol: "HRHNEXT.SME", name: "HRH Next Services Limited" },
  { symbol: "HVAX.SME", name: "HVAX Technologies Limited" },
  { symbol: "IBLFL.SME", name: "IBL Finance Limited" },
  { symbol: "ICELCO.SME", name: "IC Electricals Company Limited" },
  { symbol: "IDEALTECHO.SME", name: "Ideal Technoplast Industries Limited" },
  { symbol: "IDENTICAL.SME", name: "Identical Brains Studios Limited" },
  { symbol: "IEML.SME", name: "Indian Emulsifiers Limited" },
  { symbol: "INDIFRA.SME", name: "Indifra Limited" },
  { symbol: "INFINIUM.SME", name: "Infinium Pharmachem Limited" },
  { symbol: "INFLUX.SME", name: "Influx Healthtech Limited" },
  { symbol: "INFOLLION.SME", name: "Infollion Research Services Limited" },
  { symbol: "INM.SME", name: "Interiors & More Limited" },
  { symbol: "INNOMET.SME", name: "Innomet Advanced Materials Limited" },
  { symbol: "INSPIRE.SME", name: "Inspire Films Limited" },
  { symbol: "INTEGRITY.SME", name: "Integrity Infrabuild Developers Limited" },
  { symbol: "INVICTA.SME", name: "Invicta Diagnostic Limited" },
  { symbol: "IPHL.SME", name: "Indian Phosphate Limited" },
  { symbol: "IPSL.SME", name: "Integrated Personnel Services Limited" },
  { symbol: "ISHAN.SME", name: "Ishan International Limited" },
  { symbol: "ITALIANE.SME", name: "Italian Edibles Limited" },
  { symbol: "ITTL.SME", name: "Innovative Tyres & Tubes Limited" },
  { symbol: "IWARE.SME", name: "Iware Supplychain Services Limited" },
  { symbol: "JAINAM.SME", name: "Jainam Ferro Alloys (I) Limited" },
  { symbol: "JAINIK.SME", name: "Jainik Power Cables Limited" },
  { symbol: "JAKHARIA.SME", name: "JAKHARIA FABRIC LIMITED" },
  { symbol: "JALAN.SME", name: "Jalan Transolutions (India) Limited" },
  { symbol: "JAYBEE.SME", name: "Jay Bee Laminations Limited" },
  { symbol: "JAYESH.SME", name: "Jayesh Logistics Limited" },
  { symbol: "JETKNIT.SME", name: "Jet Knitwears Limited" },
  { symbol: "JEYYAM.SME", name: "Jeyyam Global Foods Limited" },
  { symbol: "JFLLIFE.SME", name: "Jfl Life Sciences Limited" },
  { symbol: "JIWANRAM.SME", name: "Jiwanram Sheoduttrai Industries Limited" },
  { symbol: "JYOTIGLOBL.SME", name: "Jyoti Global Plast Limited" },
  { symbol: "K2INFRA.SME", name: "K2 Infragen Limited" },
  { symbol: "KALANA.SME", name: "Kalana Ispat Limited" },
  { symbol: "KANDARP.SME", name: "Kandarp Digi Smart BPO Limited" },
  { symbol: "KARNIKA.SME", name: "Karnika Industries Limited" },
  { symbol: "KATARIA.SME", name: "Kataria Industries Limited" },
  { symbol: "KAYTEX.SME", name: "Kaytex Fabrics Limited" },
  { symbol: "KCEIL.SME", name: "Kay Cee Energy & Infra Limited" },
  { symbol: "KCK.SME", name: "Kck Industries Limited" },
  { symbol: "KDL.SME", name: "Kore Digital Limited" },
  { symbol: "KEN.SME", name: "Ken Enterprises Limited" },
  { symbol: "KHFM.SME", name: "Khfm Hospitality And Facility Management Services Limited" },
  { symbol: "KKJEWELS.SME", name: "Kabra Jewels Limited" },
  { symbol: "KKVAPOW.SME", name: "KKV Agro Powers Limited" },
  { symbol: "KLL.SME", name: "Kaushalya Logistics Limited" },
  { symbol: "KODYTECH.SME", name: "Kody Technolab Limited" },
  { symbol: "KONSTELEC.SME", name: "Konstelec Engineers Limited" },
  { symbol: "KONTOR.SME", name: "Kontor Space Limited" },
  { symbol: "KORE.SME", name: "Jay Jalaram Technologies Limited" },
  { symbol: "KRISHCA.SME", name: "Krishca Strapping Solutions Limited" },
  { symbol: "KRMAYURVED.SME", name: "KRM Ayurveda Limited" },
  { symbol: "LAKSHYA.SME", name: "Lakshya Powertech Limited" },
  { symbol: "LAMOSAIC.SME", name: "Lamosaic India Limited" },
  { symbol: "LLOYDS.SME", name: "Lloyds Luxuries Limited" },
  { symbol: "LRRPL.SME", name: "Lead Reclaim And Rubber Products Limited" },
  { symbol: "MACOBSTECH.SME", name: "Macobs Technologies Limited" },
  { symbol: "MADHAVBAUG.SME", name: "Vaidya Sane Ayurved Laboratories Limited" },
  { symbol: "MADHURKNIT.SME", name: "Madhur Knit Crafts Limited" },
  { symbol: "MADHUSUDAN.SME", name: "Madhusudan Masala Limited" },
  { symbol: "MAGSON.SME", name: "Magson Retail And Distribution Limited" },
  { symbol: "MAHICKRA.SME", name: "Mahickra Chemicals Limited" },
  { symbol: "MAITREYA.SME", name: "Maitreya Medicare Limited" },
  { symbol: "MAKS.SME", name: "Maks Energy Solutions India Limited" },
  { symbol: "MAL.SME", name: "Mangalam Alloys Limited" },
  { symbol: "MANAV.SME", name: "Manav Infra Projects Limited" },
  { symbol: "MANDEEP.SME", name: "Mandeep Auto Industries Limited" },
  { symbol: "MANILAM.SME", name: "Manilam Industries India Limited" },
  { symbol: "MARC.SME", name: "Marc Technocrats Limited" },
  { symbol: "MARCO.SME", name: "Marco Cables & Conductors Limited" },
  { symbol: "MARINETRAN.SME", name: "Marinetrans India Limited" },
  { symbol: "MARUSHIKA.SME", name: "Marushika Technology Limited" },
  { symbol: "MASON.SME", name: "Mason Infratech Limited" },
  { symbol: "MASTER.SME", name: "Master Components Limited" },
  { symbol: "MAXPOSURE.SME", name: "Maxposure Limited" },
  { symbol: "MAXVOLT.SME", name: "Maxvolt Energy Industries Limited" },
  { symbol: "MAYASHEEL.SME", name: "Mayasheel Ventures Limited" },
  { symbol: "MCON.SME", name: "Mcon Rasayan India Limited" },
  { symbol: "MDL.SME", name: "Marvel Decor Limited" },
  { symbol: "MEDIORG.SME", name: "Medicamen Organics Limited" },
  { symbol: "MEDISTEP.SME", name: "Medistep Healthcare Limited" },
  { symbol: "MEGAFLEX.SME", name: "Mega Flex Plastics Limited" },
  { symbol: "MEGATHERM.SME", name: "Megatherm Induction Limited" },
  { symbol: "METALIC.SME", name: "Metalic Technoforge Limited" },
  { symbol: "MGSL.SME", name: "Matrix Geo Solutions Limited" },
  { symbol: "MHHL.SME", name: "Mohini Health & Hygiene Limited" },
  { symbol: "MICROPRO.SME", name: "Micropro Software Solutions Limited" },
  { symbol: "MIEL.SME", name: "Manglam Infra & Engineering Limited" },
  { symbol: "MILTON.SME", name: "Milton Industries Limited" },
  { symbol: "MINDPOOL.SME", name: "Mindpool Technologies Limited" },
  { symbol: "MMEL.SME", name: "Moving Media Entertainment Limited" },
  { symbol: "MOBILISE.SME", name: "Mobilise App Lab Limited" },
  { symbol: "MONOLITH.SME", name: "Monolithisch India Limited" },
  { symbol: "MONOPHARMA.SME", name: "Mono Pharmacare Limited" },
  { symbol: "MOS.SME", name: "Mos Utility Limited" },
  { symbol: "MOXSH.SME", name: "Moxsh Overseas Educon Limited" },
  { symbol: "MPEL.SME", name: "Manas Polymers and Energies Limited" },
  { symbol: "MPEL-RE.SME", name: "Manas Polymers and Energies Limited-RE" },
  { symbol: "MPTODAY.SME", name: "Madhya Pradesh Today Media Limited" },
  { symbol: "MRIL.SME", name: "Mahendra Realtors & Infrastructure Limited" },
  { symbol: "MUNISH.SME", name: "Munish Forge Limited" },
  { symbol: "MVKAGRO.SME", name: "M.V.K. Agro Food Product Limited" },
  { symbol: "MYMUDRA.SME", name: "My Mudra Fincorp Limited" },
  { symbol: "NAMAN.SME", name: "Naman Industries Proxima Limited" },
  { symbol: "NAMOEWASTE.SME", name: "Namo eWaste Management Limited" },
  { symbol: "NEELAM.SME", name: "Neelam Linens and Garments (India) Limited" },
  { symbol: "NEOCHEM.SME", name: "Neochem Bio Solutions Limited" },
  { symbol: "NEPHROCARE.SME", name: "Nephro Care India Limited" },
  { symbol: "NEPTUNE.SME", name: "Neptune Petrochemicals Limited" },
  { symbol: "NEWJAISA.SME", name: "Newjaisa Technologies Limited" },
  { symbol: "NFPSAMPOOR.SME", name: "NFP Sampoorna Foods Limited" },
  { symbol: "NIDAN.SME", name: "Nidan Laboratories and Healthcare Limited" },
  { symbol: "NIKITA.SME", name: "NIKITA GREENTECH RECYCLING LIMITED" },
  { symbol: "NIRMAN.SME", name: "Nirman Agri Genetics Limited" },
  { symbol: "NMSTEEL.SME", name: "Newmalayalam Steel Limited" },
  { symbol: "NRVANDANA.SME", name: "N R Vandana Tex Industries Limited" },
  { symbol: "OBSCP.SME", name: "OBSC Perfection Limited" },
  { symbol: "OLIL.SME", name: "Oneclick Logistics India Limited" },
  { symbol: "OMFURN.SME", name: "Omfurn India Limited" },
  { symbol: "ONDOOR.SME", name: "On Door Concepts Limited" },
  { symbol: "ONYX.SME", name: "Onyx Biotec Limited" },
  { symbol: "OPTIMYSTIX.SME", name: "Optimystix Entertainment India Limited" },
  { symbol: "OPTIVALUE.SME", name: "Optivalue Tek Consulting Limited" },
  { symbol: "ORIANA.SME", name: "Oriana Power Limited" },
  { symbol: "OSELDEVICE.SME", name: "Osel Devices Limited" },
  { symbol: "OWAIS.SME", name: "Owais Metal And Mineral Processing Limited" },
  { symbol: "PARAGON.SME", name: "Paragon Fine and Speciality Chemical Limited" },
  { symbol: "PARAMATRIX.SME", name: "Paramatrix Technologies Limited" },
  { symbol: "PARAMOUNT.SME", name: "Paramount Dye Tec Limited" },
  { symbol: "PARAMPARA.SME", name: "PARAMPARA DAIRY DELIGHTS LIMITED" },
  { symbol: "PARIN.SME", name: "Parin Enterprises Limited" },
  { symbol: "PARTH.SME", name: "Parth Electricals & Engineering Limited" },
  { symbol: "PARTYCRUS.SME", name: "Party Cruisers Limited" },
  { symbol: "PATILAUTOM.SME", name: "Patil Automation Limited" },
  { symbol: "PATTECH.SME", name: "Pattech Fitwell Tube Components Limited" },
  { symbol: "PCCL.SME", name: "Petro Carbon and Chemicals Limited" },
  { symbol: "PELATRO.SME", name: "Pelatro Limited" },
  { symbol: "PENTAGON.SME", name: "Pentagon Rubber Limited" },
  { symbol: "PERFECT.SME", name: "Perfect Infraengineers Limited" },
  { symbol: "PHANTOMFX.SME", name: "Phantom Digital Effects Limited" },
  { symbol: "PHOGLOBAL.SME", name: "Phoenix Overseas Limited" },
  { symbol: "PLADAINFO.SME", name: "Plada Infotech Services Limited" },
  { symbol: "POLYSIL.SME", name: "Polysil Irrigation Systems Limited" },
  { symbol: "POSITRON.SME", name: "Positron Energy Limited" },
  { symbol: "PPSL.SME", name: "Picturepost Studios Limited" },
  { symbol: "PRAMARA.SME", name: "Pramara Promotions Limited" },
  { symbol: "PRAMODINI.SME", name: "Pramodini Medicare Limited" },
  { symbol: "PRANIK.SME", name: "Pranik Logistics Limited" },
  { symbol: "PRATHAM.SME", name: "Pratham EPC Projects Limited" },
  { symbol: "PRECISION.SME", name: "Precision Metaliks Limited" },
  { symbol: "PREMIUM.SME", name: "Premium Plast Limited" },
  { symbol: "PRESSTONIC.SME", name: "Presstonic Engineering Limited" },
  { symbol: "PRIMECAB.SME", name: "Prime Cable Industries Limited" },
  { symbol: "PRITIKA.SME", name: "Pritika Engineering Components Limited" },
  { symbol: "PRIZOR.SME", name: "Prizor Viztech Limited" },
  { symbol: "PRLIND.SME", name: "Premier Roadlines Limited" },
  { symbol: "PROFX.SME", name: "Pro FX Tech Limited" },
  { symbol: "PROLIFE.SME", name: "Prolife Industries Limited" },
  { symbol: "PROPEQUITY.SME", name: "P. E. Analytics Limited" },
  { symbol: "PROPSHOP.SME", name: "Propshop Events and Exhibitions Limited" },
  { symbol: "PROV.SME", name: "Proventus Agrocom Limited" },
  { symbol: "PSFL.SME", name: "Paramount Speciality Forgings Limited" },
  { symbol: "PSRAJ.SME", name: "P S Raj Steels Limited" },
  { symbol: "PULZ.SME", name: "Pulz Electronics Limited" },
  { symbol: "PURPLEUTED.SME", name: "Purple United Sales Limited" },
  { symbol: "PURVFLEXI.SME", name: "Purv Flexipack Limited" },
  { symbol: "PUSHPA.SME", name: "Pushpa Jewellers Limited" },
  { symbol: "QFIL.SME", name: "Quality Foils (India) Limited" },
  { symbol: "QLINE.SME", name: "Q-Line Biotech Limited" },
  { symbol: "QUADPRO.SME", name: "Quadpro Ites Limited" },
  { symbol: "QUALIANCE.SME", name: "Qualiance International Limited" },
  { symbol: "QUESTLAB.SME", name: "Quest Laboratories Limited" },
  { symbol: "QUICKTOUCH.SME", name: "Quicktouch Technologies Limited" },
  { symbol: "QVCEL.SME", name: "QVC Exports Limited" },
  { symbol: "RADIOWALLA.SME", name: "Radiowalla Network Limited" },
  { symbol: "RAJINDLTD.SME", name: "Rajputana Industries Limited" },
  { symbol: "RAJPUTANA.SME", name: "Rajputana Biodiesel Limited" },
  { symbol: "RAPIDFLEET.SME", name: "Rapid Fleet Management Services Limited" },
  { symbol: "RAPPID.SME", name: "Rappid Valves (India) Limited" },
  { symbol: "RBMINFRA.SME", name: "Rbm Infracon Limited" },
  { symbol: "RBS.SME", name: "Ramdevbaba Solvent Limited" },
  { symbol: "RCDL.SME", name: "Rajgor Castor Derivatives Limited" },
  { symbol: "RCDL-RE.SME", name: "Rajgor Castor Derivatives Limited-RE" },
  { symbol: "READYMIX.SME", name: "Readymix Construction Machinery Limited" },
  { symbol: "REFRACTORY.SME", name: "Refractory Shapes Limited" },
  { symbol: "REMUS.SME", name: "Remus Pharmaceuticals Limited" },
  { symbol: "REXPIPES.SME", name: "Rex Pipes And Cables Industries Limited" },
  { symbol: "REXPRO.SME", name: "Rexpro Enterprises Limited" },
  { symbol: "RFBL.SME", name: "RFBL Flexi Pack Limited" },
  { symbol: "RICHA.SME", name: "Richa Info Systems Limited" },
  { symbol: "RILINFRA.SME", name: "Rachana Infrastructure Limited" },
  { symbol: "RITEZONE.SME", name: "Rite Zone Chemcon India Limited" },
  { symbol: "RNFI.SME", name: "RNFI Services Limited" },
  { symbol: "RNPL.SME", name: "Renol Polychem Limited" },
  { symbol: "ROCKINGDCE.SME", name: "Rockingdeals Circular Economy Limited" },
  { symbol: "ROXHITECH.SME", name: "Rox Hi Tech Limited" },
  { symbol: "ROYALARC.SME", name: "Royal Arc Electrodes Limited" },
  { symbol: "RTL.SME", name: "Rama Telecom Limited" },
  { symbol: "RULKA.SME", name: "Rulka Electricals Limited" },
  { symbol: "SAAKSHI.SME", name: "Saakshi Medtech and Panels Limited" },
  { symbol: "SABAR.SME", name: "Sabar Flex India Limited" },
  { symbol: "SACHEEROME.SME", name: "Sacheerome Limited" },
  { symbol: "SADHAV.SME", name: "Sadhav Shipping Limited" },
  { symbol: "SAFEENTP.SME", name: "Safe Enterprises Retail Fixtures Limited" },
  { symbol: "SAHAJSOLAR.SME", name: "Sahaj Solar Limited" },
  { symbol: "SAHANA.SME", name: "Sahana System Limited" },
  { symbol: "SAHASRA.SME", name: "Sahasra Electronic Solutions Limited" },
  { symbol: "SAIFL.SME", name: "Sameera Agro And Infra Limited" },
  { symbol: "SAJHOTELS.SME", name: "Saj Hotels Limited" },
  { symbol: "SAMAY.SME", name: "Samay Project Services Limited" },
  { symbol: "SANGANI.SME", name: "Sangani Hospitals Limited" },
  { symbol: "SAROJA.SME", name: "Saroja Pharma Industries India Limited" },
  { symbol: "SARTELE.SME", name: "Sar Televenture Limited" },
  { symbol: "SATECH.SME", name: "S A Tech Software India Limited" },
  { symbol: "SATIPOLY.SME", name: "Sati Poly Plast Limited" },
  { symbol: "SATKARTAR.SME", name: "Sat Kartar Life Limited" },
  { symbol: "SATTVAENGG.SME", name: "Sattva Engineering Construction Limited" },
  { symbol: "SAVY.SME", name: "Savy Infra and Logistics Limited" },
  { symbol: "SAWALIYA.SME", name: "Sawaliya Food Products Limited" },
  { symbol: "SCML.SME", name: "Sharp Chucks and Machines Limited" },
  { symbol: "SDREAMS.SME", name: "S D Retail Limited" },
  { symbol: "SEL.SME", name: "Sungarner Energies Limited" },
  { symbol: "SELLOWRAP.SME", name: "Sellowrap Industries Limited" },
  { symbol: "SERVICE.SME", name: "Service Care Limited" },
  { symbol: "SFML.SME", name: "Supreme Facility Management Limited" },
  { symbol: "SHAIVAL.SME", name: "Shaival Reality Limited" },
  { symbol: "SHANTHALA.SME", name: "Shanthala FMCG Products Limited" },
  { symbol: "SHANTIINOR.SME", name: "Shanti Inorganics Limited" },
  { symbol: "SHEEL.SME", name: "Sheel Biotech Limited" },
  { symbol: "SHEETAL.SME", name: "Sheetal Universal Limited" },
  { symbol: "SHERA.SME", name: "Shera Energy Limited" },
  { symbol: "SHETHJI.SME", name: "Shreeji Global FMCG Limited" },
  { symbol: "SHIGAN.SME", name: "Shigan Quantum Technologies Limited" },
  { symbol: "SHIVASHRIT.SME", name: "Shivashrit Foods Limited" },
  { symbol: "SHKSIL.SME", name: "Shri Hare-Krishna Sponge Iron Limited" },
  { symbol: "SHREEDHAR.SME", name: "Shreedhar Spinners Limited" },
  { symbol: "SHREEKARNI.SME", name: "Shree Karni Fabcom Limited" },
  { symbol: "SHREEOSFM.SME", name: "Shree OSFM E-Mobility Limited" },
  { symbol: "SHRIAHIMSA.SME", name: "Shri Ahimsa Naturals Limited" },
  { symbol: "SHRIKANHA.SME", name: "Shri Kanha Stainless Limited" },
  { symbol: "SHRITECH.SME", name: "Shri Techtex Limited" },
  { symbol: "SHUBHLAXMI.SME", name: "Shubhlaxmi Jewel Art Limited" },
  { symbol: "SHUBHSHREE.SME", name: "Shubhshree Biofuels Energy Limited" },
  { symbol: "SHYAMDHANI.SME", name: "Shyam Dhani Industries Limited" },
  { symbol: "SIDDHICOTS.SME", name: "Siddhi Cotspin Limited" },
  { symbol: "SIDDHIKA.SME", name: "Siddhika Coatings Limited" },
  { symbol: "SIGNORIA.SME", name: "Signoria Creation Limited" },
  { symbol: "SILKFLEX.SME", name: "Silkflex Polymers (India) Limited" },
  { symbol: "SILKY.SME", name: "Silky Overseas Limited" },
  { symbol: "SIMCA.SME", name: "Simca Advertising Limited" },
  { symbol: "SJLOGISTIC.SME", name: "S J Logistics (India) Limited" },
  { symbol: "SKP.SME", name: "SKP Bearing Industries Limited" },
  { symbol: "SKYTECH.SME", name: "Skytech Infinite Platform Limited" },
  { symbol: "SLONE.SME", name: "Slone Infosystems Limited" },
  { symbol: "SMARTEN.SME", name: "Smarten Power Systems Limited" },
  { symbol: "SMVD.SME", name: "SMVD Poly Pack Limited" },
  { symbol: "SNEHAA.SME", name: "Snehaa Organics Limited" },
  { symbol: "SOCL.SME", name: "Sundrex Oil Company Limited" },
  { symbol: "SONAMAC.SME", name: "Sona Machinery Limited" },
  { symbol: "SONUINFRA.SME", name: "Sonu Infratech Limited" },
  { symbol: "SOTAC.SME", name: "Sotac Pharmaceuticals Limited" },
  { symbol: "SPCL.SME", name: "Shivalic Power Control Limited" },
  { symbol: "SPCON.SME", name: "Srinibas Pradhan Constructions Limited" },
  { symbol: "SPEB.SME", name: "Speb Adhesives Limited" },
  { symbol: "SPECTSTM.SME", name: "Spectrum Talent Management Limited" },
  { symbol: "SPPPOLY.SME", name: "SPP Polymer Limited" },
  { symbol: "SPRL.SME", name: "Sp Refractories Limited" },
  { symbol: "SPUNWEB.SME", name: "Spunweb Nonwoven Limited" },
  { symbol: "SRIVASAVI.SME", name: "Srivasavi Adhesive Tapes Limited" },
  { symbol: "SSEGL.SME", name: "Sathlokhar Synergys E&C Global Limited" },
  { symbol: "SSFL.SME", name: "Srivari Spices And Foods Limited" },
  { symbol: "STRIDERS.SME", name: "Striders Impex Limited" },
  { symbol: "STUDIOLSD.SME", name: "Studio LSD Limited" },
  { symbol: "SUBAHOTELS.SME", name: "Suba Hotels Limited" },
  { symbol: "SUMAX.SME", name: "Sumax Engineering Limited" },
  { symbol: "SUNLITE.SME", name: "Sunlite Recycling Industries Limited" },
  { symbol: "SUNREST.SME", name: "Sunrest Lifescience Limited" },
  { symbol: "SUNTECH.SME", name: "Suntech Infra Solutions Limited" },
  { symbol: "SUPREMEPWR.SME", name: "Supreme Power Equipment Limited" },
  { symbol: "SURANI.SME", name: "Surani Steel Tubes Limited" },
  { symbol: "SWASTIK.SME", name: "Swastik Pipe Limited" },
  { symbol: "SYLVANPLY.SME", name: "Sylvan Plyboard (India) Limited" },
  { symbol: "SYNOPTICS.SME", name: "Synoptics Technologies Limited" },
  { symbol: "SYSTANGO.SME", name: "Systango Technologies Limited" },
  { symbol: "TAC.SME", name: "TAC Infosec Limited" },
  { symbol: "TANKUP.SME", name: "Tankup Engineers Limited" },
  { symbol: "TAPIFRUIT.SME", name: "Tapi Fruit Processing Limited" },
  { symbol: "TAURIAN.SME", name: "Taurian MPS Limited" },
  { symbol: "TBI.SME", name: "TBI Corn Limited" },
  { symbol: "TCL.SME", name: "Thaai Casting Limited" },
  { symbol: "TEAMTECH.SME", name: "Teamtech Formwork Solutions Limited" },
  { symbol: "TECHD.SME", name: "TechD Cybersecurity Limited" },
  { symbol: "TECHERA.SME", name: "TechEra Engineering (India) Limited" },
  { symbol: "TECHLABS.SME", name: "Trident Techlabs Limited" },
  { symbol: "TEJA.SME", name: "Teja Engineering Industries Limited" },
  { symbol: "TEJASCARGO.SME", name: "Tejas Cargo India Limited" },
  { symbol: "TGL.SME", name: "Teerth Gopicon Limited" },
  { symbol: "THESL.SME", name: "Thinking Hats Entertainment Solutions Limited" },
  { symbol: "TIMESCAN.SME", name: "Timescan Logistics (India) Limited" },
  { symbol: "TIRUPATI.SME", name: "Shree Tirupati Balajee FIBC Limited" },
  { symbol: "TRANSTEEL.SME", name: "Transteel Seating Technologies Limited" },
  { symbol: "TRANSWIND.SME", name: "Transwind Infrastructures Limited" },
  { symbol: "TRIDHYA.SME", name: "Tridhya Tech Limited" },
  { symbol: "TROM.SME", name: "Trom Industries Limited" },
  { symbol: "TRUST.SME", name: "Trust Fintech Limited" },
  { symbol: "TSC.SME", name: "TSC India Limited" },
  { symbol: "TUNWAL.SME", name: "Tunwal E-Motors Limited" },
  { symbol: "UCL.SME", name: "Ushanti Colour Chem Limited" },
  { symbol: "UHTL.SME", name: "United Heat Transfer Limited" },
  { symbol: "UMA.SME", name: "Uma Converter Limited" },
  { symbol: "UNIHEALTH.SME", name: "Unihealth Hospitals Limited" },
  { symbol: "UNILEX.SME", name: "Unilex Colours and Chemicals Limited" },
  { symbol: "URBAN.SME", name: "Urban Enviro Waste Management Limited" },
  { symbol: "USASEEDS.SME", name: "Upsurge Seeds Of Agriculture Limited" },
  { symbol: "USHAFIN.SME", name: "Usha Financial Services Limited" },
  { symbol: "UTKAL.SME", name: "Utkal Speciality Industries India Limited" },
  { symbol: "UTSSAV.SME", name: "Utssav CZ Gold Jewels Limited" },
  { symbol: "UWCSL.SME", name: "Ultra Wiring Connectivity System Limited" },
  { symbol: "VALUE360.SME", name: "Value 360 Communications Limited" },
  { symbol: "VASA.SME", name: "Vasa Retail and Overseas Ltd" },
  { symbol: "VDEAL.SME", name: "Vdeal System Limited" },
  { symbol: "VEEKAYEM.SME", name: "Veekayem Fashion and Apparels Limited" },
  { symbol: "VELS.SME", name: "Vels Film International Limited" },
  { symbol: "VERA.SME", name: "Vera Synthetic Limited" },
  { symbol: "VERITAAS.SME", name: "Veritaas Advertising Limited" },
  { symbol: "VERTEXPLUS.SME", name: "Vertexplus Technologies Limited" },
  { symbol: "VGINFOTECH.SME", name: "Virtual Galaxy Infotech Limited" },
  { symbol: "VIAZ.SME", name: "Viaz Tyres Limited" },
  { symbol: "VICTORYEV.SME", name: "Victory Electric Vehicles International Limited" },
  { symbol: "VIESL.SME", name: "Vision Infra Equipment Solutions Limited" },
  { symbol: "VIGOR.SME", name: "Vigor Plast India Limited" },
  { symbol: "VIJAYPD.SME", name: "Vijaypd Ceutical Limited" },
  { symbol: "VILAS.SME", name: "Vilas Transcore Limited" },
  { symbol: "VILINBIO.SME", name: "Vilin Bio Med Limited" },
  { symbol: "VINOD.SME", name: "Vinod Texworld Limited" },
  { symbol: "VINSYS.SME", name: "Vinsys IT Services India Limited" },
  { symbol: "VINYAS.SME", name: "Vinyas Innovative Technologies Limited" },
  { symbol: "VISAMAN.SME", name: "Visaman Global Sales Limited" },
  { symbol: "VISDEM.SME", name: "Visdem Technosys Limited" },
  { symbol: "VISHNUINFR.SME", name: "Vishnusurya Projects and Infra Limited" },
  { symbol: "VISHWAS.SME", name: "Vishwas Agri Seeds Limited" },
  { symbol: "VIVIDEL.SME", name: "Vivid Electromech Limited" },
  { symbol: "VIVO.SME", name: "Vivo Collaboration Solutions Limited" },
  { symbol: "VLINFRA.SME", name: "V.L.Infraprojects Limited" },
  { symbol: "VMARCIND.SME", name: "V Marc India Limited" },
  { symbol: "VMOBILE.SME", name: "Vinit Mobile Limited" },
  { symbol: "VOLERCAR.SME", name: "Voler Car Limited" },
  { symbol: "VR.SME", name: "V R Infraspace Limited" },
  { symbol: "VSCL.SME", name: "Vadivarhe Speciality Chemicals Limited" },
  { symbol: "WALPAR.SME", name: "Walpar Nutritions Limited" },
  { symbol: "WHITEFORCE.SME", name: "Happy Square Outsourcing Services Limited" },
  { symbol: "WINNY.SME", name: "Winny Immigration & Education Services Limited" },
  { symbol: "WINSOL.SME", name: "Winsol Engineers Limited" },
  { symbol: "WOL3D.SME", name: "Wol 3D India Limited" },
  { symbol: "WOMANCART.SME", name: "Womancart Limited" },
  { symbol: "WTICAB.SME", name: "Wise Travel India Limited" },
  { symbol: "YAAP.SME", name: "Yaap Digital Limited" },
  { symbol: "YASHOPTICS.SME", name: "Yash Optics & Lens Limited" },
  { symbol: "YCCL.SME", name: "Yasons Chemex Care Limited" },
  { symbol: "YUDIZ.SME", name: "Yudiz Solutions Limited" },
  { symbol: "ZEAL.SME", name: "Zeal Global Services Limited" },
  { symbol: "ZENITHDRUG.SME", name: "Zenith Drugs Limited" },
  { symbol: "ZTECH.SME", name: "Z-Tech (India) Limited" },
    ],
  },
];
